FROM ruby:2.6.9
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN git config --global url."https://github.com/".insteadOf git://github.com/
RUN bundle install
ADD . /app
